_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.9.15
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 1
                - 2
                - 3
                - 13
                - 16
                - 23
                - 55
                - 62
            "4": 3.9.15
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
device:
    value: cuda
instruments:
    value:
        - BTC_USDC-PERPETUAL
model_params:
    value:
        dropout: 0.2
        max_seq_length: 512
        tcn_channels:
            - 32
            - 32
        tcn_kernel_size: 3
        transformer_dim: 32
        transformer_heads: 2
        transformer_layers: 2
training_params:
    value:
        batch_size: 32
        gradient_accumulation: 2
        learning_rate: 0.001
        num_epochs: 3
        num_workers: 2
        patience: 3
        seq_length: 32
        weight_decay: 0.0001
